# This CI setup forces the paper to build using a simple `latexmk` command.

name: paper build CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: LaTeX compilation
      uses: dante-ev/latex-action@2021-A
      with:
        # The root LaTeX file to be compiled
        root_file: paper.tex
